# Compose file for building the Polari Frontend Project independently
version: '3.7'
services:
  polari-frontend:
    build:
      context: . #Builds polari frontend from the same working directory
    restart: always
    ports: 
      - "4200:4200" #Builds the default setting ports and maps the port to the localhost port 4200.